### PR TITLE
Just reverse without sort. (So reverse-sort = sort + reverse).

### PR DESCRIPTION
**Pull request by xpol**
As discussed in #20 . I think separate sort and reverse would be more flexible.

### CODE REVIEW

**Comment by kevinsawicki** [comment]
I still think it would be nice to keep reverse sort instead of forcing to people to run sort and then reverse.

What do you think about just adding reverse, and leaving reverse-sort there as is?

**Comment by xpol** [comment]
I have forked and renamed new package to `lines`.

**Comment by edwardsgs** [comment]
@xpol I see this issue is resolved. But when should the reverse function be available? I have version 1.0.19 but I don't see a function for reversing lines in a file.

**Comment by xpol** [comment]
@edwardsgs You might need try my fork [lines](https://atom.io/packages/lines) .

**Comment by edwardsgs** [comment]
Ahhh. I was confused at first. I thought your package was an update to the base product. Now I see its an add-on package. I added it and it implements reverse exactly the way I needed. Thanks!

**Pull request closed without merging**
