### PR TITLE
Support sorting words within selection(s)

### PR DESCRIPTION
**Pull request by AndiDog**
I thought everything related to sorting might be a good feature for this core package, so I added a "sort words" feature.

Example: `git nginx curl` would be sorted to `curl git nginx`

### CODE REVIEW

**Comment by AndiDog** [comment]
If you think this is a good idea, I could improve it for even more use cases like comma-separated words etc.

**Comment by Misioka** [comment]
I would like ot use it when i sort inline react props
<SomeComponent title='title' aprop={this.props.aprop} />
sort to:
<SomeComponent aprop={this.props.aprop} title='title' />

**Comment by rasenplanscher** [comment]
What about [sort-words](https://atom.io/packages/sort-words)?

Also, this addresses pretty much #43 – should be linked, I think

**Comment by AndiDog** [comment]
I think the sort-lines package is much easier to extend (check sort-words package's code), and for me it makes more sense to have the functionality and sane tests within one, well-maintained package.

**Comment by rasenplanscher** [comment]
I do get the motivation. However, that way of reasoning leads to monoliths. I think it would be better to actually bring [sort-words](https://atom.io/packages/sort-words) up to quality. You know, spread the word instead of building castles...

**Comment by AndiDog** [comment]
I'm happy to edit either package. To avoid misunderstanding: my comment was not about quality, but extensibility. sort-lines seemed to me like the best practice "sorts all your things" which already has prepared code for selecting ranges etc., while sort-words isn't yet made in that way.

But to continue discussion, @jamesgraham10 do you think I could provide some refactoring (such as using selection ranges) for your sort-words package in order to make it testable and then extend with some features: regular, case-insensitive, comma-separated sorting and whatever people find useful?

**Comment by jamesgraham10** [comment]
Hi @AndiDog. My sort-words package was more of an experiment as I wanted to learn the basics of making Atom Packages but it would be awesome if it was taken further. So yeah any refactoring / improvements would be most welcome. Thanks!

**Comment by rasenplanscher** [comment]
Sounds great 😄 

@AndiDog Based on your comment, I took a look at the `RangeFinder` in `sort-lines`. I think, `sort-words` does not have the same need, in that it would never sort the whole file but always a selection. Therefore, I think the range-finding points towards `sort-words` as well.

**Comment by AndiDog** [comment]
Thanks all! Nevertheless the effort was not wasted, since **I** learned the basics of package development with this change. Closing this PR in favor of supporting the sort-words package. Soon to come whenever I find the time!

**Pull request closed without merging**
