### PR TITLE
Support natural sorting

### LINKED ISSUE #47: Natural Sort
I often want to sort lists of numbers and a natural sort would be helpful.

### PR DESCRIPTION
**Pull request by anderoonies**
taking a stab at #47 
i think the specs are exhaustive and independent, if anyone finds fault with them or comes up with others let me know 

Closes #47

### CODE REVIEW

**Comment by lee-dohm** [comment]
Looks good to me :+1: 

/cc @atom/feedback

**Comment by 50Wliu** [comment]
Looks good to me as well!

**Comment by lee-dohm** [comment]
Thanks for contributing!

**Comment by anderoonies** [comment]
@lee-dohm my pleasure! looking forward to contributing more.

**Pull request merged**
